// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: idl/agentcore.proto

package agentcore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentCoreService_CreateCodeInterpreter_FullMethodName = "/agentland.agentcore.v1.AgentCoreService/CreateCodeInterpreter"
	AgentCoreService_CreateAgentSession_FullMethodName    = "/agentland.agentcore.v1.AgentCoreService/CreateAgentSession"
	AgentCoreService_GetAgentSession_FullMethodName       = "/agentland.agentcore.v1.AgentCoreService/GetAgentSession"
	AgentCoreService_DeleteAgentSession_FullMethodName    = "/agentland.agentcore.v1.AgentCoreService/DeleteAgentSession"
)

// AgentCoreServiceClient is the client API for AgentCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentCoreServiceClient interface {
	CreateCodeInterpreter(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	CreateAgentSession(ctx context.Context, in *CreateAgentSessionRequest, opts ...grpc.CallOption) (*CreateAgentSessionResponse, error)
	GetAgentSession(ctx context.Context, in *GetAgentSessionRequest, opts ...grpc.CallOption) (*GetAgentSessionResponse, error)
	DeleteAgentSession(ctx context.Context, in *DeleteAgentSessionRequest, opts ...grpc.CallOption) (*DeleteAgentSessionResponse, error)
}

type agentCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentCoreServiceClient(cc grpc.ClientConnInterface) AgentCoreServiceClient {
	return &agentCoreServiceClient{cc}
}

func (c *agentCoreServiceClient) CreateCodeInterpreter(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, AgentCoreService_CreateCodeInterpreter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoreServiceClient) CreateAgentSession(ctx context.Context, in *CreateAgentSessionRequest, opts ...grpc.CallOption) (*CreateAgentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentSessionResponse)
	err := c.cc.Invoke(ctx, AgentCoreService_CreateAgentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoreServiceClient) GetAgentSession(ctx context.Context, in *GetAgentSessionRequest, opts ...grpc.CallOption) (*GetAgentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentSessionResponse)
	err := c.cc.Invoke(ctx, AgentCoreService_GetAgentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentCoreServiceClient) DeleteAgentSession(ctx context.Context, in *DeleteAgentSessionRequest, opts ...grpc.CallOption) (*DeleteAgentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentSessionResponse)
	err := c.cc.Invoke(ctx, AgentCoreService_DeleteAgentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentCoreServiceServer is the server API for AgentCoreService service.
// All implementations must embed UnimplementedAgentCoreServiceServer
// for forward compatibility.
type AgentCoreServiceServer interface {
	CreateCodeInterpreter(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	CreateAgentSession(context.Context, *CreateAgentSessionRequest) (*CreateAgentSessionResponse, error)
	GetAgentSession(context.Context, *GetAgentSessionRequest) (*GetAgentSessionResponse, error)
	DeleteAgentSession(context.Context, *DeleteAgentSessionRequest) (*DeleteAgentSessionResponse, error)
	mustEmbedUnimplementedAgentCoreServiceServer()
}

// UnimplementedAgentCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentCoreServiceServer struct{}

func (UnimplementedAgentCoreServiceServer) CreateCodeInterpreter(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCodeInterpreter not implemented")
}
func (UnimplementedAgentCoreServiceServer) CreateAgentSession(context.Context, *CreateAgentSessionRequest) (*CreateAgentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentSession not implemented")
}
func (UnimplementedAgentCoreServiceServer) GetAgentSession(context.Context, *GetAgentSessionRequest) (*GetAgentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentSession not implemented")
}
func (UnimplementedAgentCoreServiceServer) DeleteAgentSession(context.Context, *DeleteAgentSessionRequest) (*DeleteAgentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgentSession not implemented")
}
func (UnimplementedAgentCoreServiceServer) mustEmbedUnimplementedAgentCoreServiceServer() {}
func (UnimplementedAgentCoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentCoreServiceServer will
// result in compilation errors.
type UnsafeAgentCoreServiceServer interface {
	mustEmbedUnimplementedAgentCoreServiceServer()
}

func RegisterAgentCoreServiceServer(s grpc.ServiceRegistrar, srv AgentCoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentCoreService_ServiceDesc, srv)
}

func _AgentCoreService_CreateCodeInterpreter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServiceServer).CreateCodeInterpreter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoreService_CreateCodeInterpreter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServiceServer).CreateCodeInterpreter(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoreService_CreateAgentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServiceServer).CreateAgentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoreService_CreateAgentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServiceServer).CreateAgentSession(ctx, req.(*CreateAgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoreService_GetAgentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServiceServer).GetAgentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoreService_GetAgentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServiceServer).GetAgentSession(ctx, req.(*GetAgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentCoreService_DeleteAgentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentCoreServiceServer).DeleteAgentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentCoreService_DeleteAgentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentCoreServiceServer).DeleteAgentSession(ctx, req.(*DeleteAgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentCoreService_ServiceDesc is the grpc.ServiceDesc for AgentCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentland.agentcore.v1.AgentCoreService",
	HandlerType: (*AgentCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCodeInterpreter",
			Handler:    _AgentCoreService_CreateCodeInterpreter_Handler,
		},
		{
			MethodName: "CreateAgentSession",
			Handler:    _AgentCoreService_CreateAgentSession_Handler,
		},
		{
			MethodName: "GetAgentSession",
			Handler:    _AgentCoreService_GetAgentSession_Handler,
		},
		{
			MethodName: "DeleteAgentSession",
			Handler:    _AgentCoreService_DeleteAgentSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/agentcore.proto",
}

const (
	SandboxService_ExecuteCode_FullMethodName = "/agentland.agentcore.v1.SandboxService/ExecuteCode"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxServiceClient interface {
	ExecuteCode(ctx context.Context, in *ExecuteCodeRequest, opts ...grpc.CallOption) (*ExecuteCodeResponse, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) ExecuteCode(ctx context.Context, in *ExecuteCodeRequest, opts ...grpc.CallOption) (*ExecuteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCodeResponse)
	err := c.cc.Invoke(ctx, SandboxService_ExecuteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
type SandboxServiceServer interface {
	ExecuteCode(context.Context, *ExecuteCodeRequest) (*ExecuteCodeResponse, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) ExecuteCode(context.Context, *ExecuteCodeRequest) (*ExecuteCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_ExecuteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).ExecuteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_ExecuteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).ExecuteCode(ctx, req.(*ExecuteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentland.agentcore.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCode",
			Handler:    _SandboxService_ExecuteCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/agentcore.proto",
}
