FROM golang:1.25.5-alpine AS builder

ARG TARGETOS=linux
ARG TARGETARCH

ENV GOPROXY='https://goproxy.cn,direct'

WORKDIR /workspace

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/
COPY internal/ internal/
COPY api/ api/
COPY pb/ pb/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-s -w" -o korokd ./cmd/korokd

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
      bash \
      curl \
      git openssh-client \
      jq \
      procps \
      iproute2 \
      python3 python3-pip \
      tini \
    && rm -rf /var/lib/apt/lists/*

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN python3 -m pip install --no-cache-dir -U pip \
    && python3 -m pip install --no-cache-dir ipykernel==6.29.5

RUN python3 -m pip install --no-cache-dir -U pip \
 && python3 -m pip install --no-cache-dir ipykernel==6.29.5

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get update && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN npm config set fund false \
    && npm config set audit false \
    && npm i -g agent-browser \
    && agent-browser install \
    && npx playwright install-deps \
    && npm cache clean --force

WORKDIR /app

COPY --from=builder /workspace/korokd .

EXPOSE 1883

ENTRYPOINT ["/usr/bin/tini","--","/app/korokd"]
CMD ["--port=1883"]