// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Fl0rencess720/agentland/app/be/internal/biz"
	"github.com/Fl0rencess720/agentland/app/be/internal/data"
	"github.com/Fl0rencess720/agentland/app/be/internal/service"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/auth"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/deployment"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/file"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/job"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/middlewares"
	"github.com/Fl0rencess720/agentland/app/be/internal/service/project"
)

func wireApp() *App {
	ipRateLimiter := middlewares.NewDefaultIPRateLimiter()
	userRepo := data.NewUserRepo()
	authRepo := data.NewAuthRepo()
	oauthStateStore := data.NewOAuthStateStore()
	githubOAuthClient := data.NewGitHubOAuthClient()
	authUseCase := biz.NewAuthUsecase(userRepo, authRepo, oauthStateStore, githubOAuthClient)
	authHandler := auth.NewAuthHandler(authUseCase)
	projectRepo := data.NewProjectRepo()
	projectUseCase := biz.NewProjectUsecase(projectRepo)
	projectHandler := project.NewProjectHandler(projectUseCase)
	jobRepo := data.NewJobRepo()
	jobUseCase := biz.NewJobUsecase(jobRepo)
	jobHandler := job.NewJobHandler(jobUseCase)
	deploymentRepo := data.NewDeploymentRepo()
	deploymentUseCase := biz.NewDeploymentUsecase(deploymentRepo)
	deploymentHandler := deployment.NewDeploymentHandler(deploymentUseCase)
	fileRepo := data.NewFileRepo()
	fileUseCase := biz.NewFileUsecase(fileRepo)
	fileHandler := file.NewFileHandler(fileUseCase)
	httpServer := service.NewHTTPServer(ipRateLimiter, authHandler, projectHandler, jobHandler, deploymentHandler, fileHandler)
	app := NewApp(httpServer)
	return app
}

type App struct {
	HTTPServer *service.HTTPServer
}

func NewApp(httpServer *service.HTTPServer) *App {
	return &App{HTTPServer: httpServer}
}
